### ISSUE TITLE
Compatibility with Yosemite and Sierra

### ISSUE THREAD

**Issue by syxanash** [JohnDDuncanIII/Platinum#1]
Just a question before I end up breaking everything: will it work with Yosemite or newly released Sierra?

**Comment by JohnDDuncanIII** [comment]
The primary GraphiteAppearance.car is specifically for 10.11. I did make a Yosemite version, which is located [here](https://github.com/JohnDDuncanIII/Platinum/tree/master/old%20themes/10.10). 

As for Sierra, I am not sure yet. I do not have a computer to test it on (I run a 2009 MBP), but I would assume that it does not work. Anyone is free to test it out to see (make sure you make backups!), but as of right now, I don't know. [Alex Zielenski](https://github.com/alexzielenski/ThemeEngine) might know, as he created the .car editing software that I use (he also worked at Apple this summer).

**Comment by syxanash** [comment]
Alright thanks for your answer. This theme pack is awesome btw! 😃

**Comment by danyisill** [comment]
It works perfectly on Sierra (if you don't already know)

**Comment by JohnDDuncanIII** [comment]
I did not know. Thanks for testing!
